In [108]:
import pandas as pd

In [109]:
matches = pd.read_csv('../datasets/merge.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 105

In [ ]:
matches.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,D1,16/08/2019,19:30,Bayern Munich,Hertha,2,2,D,1,2,...,3.40,-2.25,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91
1,D1,17/08/2019,14:30,Dortmund,Augsburg,5,1,H,1,1,...,3.31,-2.25,1.92,2.01,1.92,2.00,1.98,2.04,1.91,1.97
2,D1,17/08/2019,14:30,Freiburg,Mainz,3,0,H,0,0,...,1.89,0.00,1.92,2.01,1.94,1.97,1.97,2.06,1.90,1.99
3,D1,17/08/2019,14:30,Leverkusen,Paderborn,3,2,H,2,2,...,3.58,-2.00,2.07,1.86,2.05,1.86,2.15,1.91,2.03,1.85
4,D1,17/08/2019,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,...,2.26,-0.75,1.92,2.01,1.92,2.00,1.95,2.11,1.89,2

In [ ]:
matches.shape

(1224, 105)

In [ ]:
matches["HomeTeam"].value_counts()

HomeTeam
Bayern Munich         68
Union Berlin          68
Hertha                68
RB Leipzig            68
Mainz                 68
Hoffenheim            68
Dortmund              68
Augsburg              68
FC Koln               68
Ein Frankfurt         68
M'gladbach            68
Wolfsburg             68
Leverkusen            68
Freiburg              68
Werder Bremen         51
Schalke 04            51
Stuttgart             51
Bielefeld             34
Bochum                34
Fortuna Dusseldorf    17
Paderborn             17
Greuther Furth        17
Name: count, dtype: int64

In [ ]:
matches[matches["HomeTeam"] == "Bayern Munich"]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,D1,16/08/2019,19:30,Bayern Munich,Hertha,2,2,D,1,2,...,3.40,-2.25,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91
19,D1,31/08/2019,14:30,Bayern Munich,Mainz,6,1,H,2,1,...,4.32,-2.75,2.05,1.88,2.03,1.88,2.11,1.90,2.02,1.86
37,D1,21/09/2019,14:30,Bayern Munich,FC Koln,4,0,H,1,0,...,4.07,-2.50,1.86,2.07,1.86,2.06,1.90,2.08,1.86,2.02
55,D1,05/10/2019,14:30,Bayern Munich,Hoffenheim,1,2,A,0,0,...,4.91,-2.75,1.94,1.99,1.92,2.00,1.98,2.03,1.93,1.95
73,D1,26/10/2019,14:30,Bayern Munich,Union Berlin,2,1,H,1,0,...,4.49,-2.75,1.96,1.97,1.95,1.96,1.99,1.99,1.95,1.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,D1,01/04/2023,17:30,Bayern Munich,Dortmund,4,2,H,3,0,...,3.07,-1.25,2.07,1.86,2.05,1.88,2.08,1.93,2.00,1.86
1162,D1,15/04/2023,14:30,Bayern Munich,Hoffenheim,1,1,D,1,0,...,4.03,-2.25,2.05,1.85,2.04,1.87,2.08,1.91,1.99,1.86
1186,D1,30/04/2023,14:30,Bayern Munich,Hertha,2,0,H,0,0,...,4.72,-2.75,1.77,2.02,1.86,2.03,1.94,2.11,1.85,2
1198,D1,13/05/2023,14:30,Bayern Munich,Schalke 04,6,0,H,2,0,...,4.77,-2.50,1.95,1.95,1.94,1.96,1.98,2.10,1.91,1.95
1211,D1,20/05/2023,17:30,Bayern Munich,RB Leipzig,1,3,A,1,0,...,3.22,-1.00,1.85,2.08,1.85,2.08,1.89,2.18,1.84,2.03

In [ ]:
matches.dtypes

Div          object
Date         object
Time         object
HomeTeam     object
AwayTeam     object
             ...
PCAHA       float64
MaxCAHH     float64
MaxCAHA     float64
AvgCAHH     float64
AvgCAHA      object
Length: 105, dtype: object

In [ ]:
matches.drop(["Div"], axis="columns", inplace=True)

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,16/08/2019,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,3.40,-2.25,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91
1,17/08/2019,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,3.31,-2.25,1.92,2.01,1.92,2.00,1.98,2.04,1.91,1.97
2,17/08/2019,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.89,0.00,1.92,2.01,1.94,1.97,1.97,2.06,1.90,1.99
3,17/08/2019,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,3.58,-2.00,2.07,1.86,2.05,1.86,2.15,1.91,2.03,1.85
4,17/08/2019,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,2.26,-0.75,1.92,2.01,1.92,2.00,1.95,2.11,1.89,2

In [ ]:
matches["Date"] = pd.to_datetime(matches["Date"])

/var/folders/lw/pygk9wrs0711t4dprf56xt_m0000gn/T/ipykernel_64151/254043194.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  matches["Date"] = pd.to_datetime(matches["Date"])

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,3.40,-2.25,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,3.31,-2.25,1.92,2.01,1.92,2.00,1.98,2.04,1.91,1.97
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.89,0.00,1.92,2.01,1.94,1.97,1.97,2.06,1.90,1.99
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,3.58,-2.00,2.07,1.86,2.05,1.86,2.15,1.91,2.03,1.85
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,2.26,-0.75,1.92,2.01,1.92,2.00,1.95,2.11,1.89,2

In [ ]:
matches["FTR_code"] = matches["FTR"].astype("category").cat.codes

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,-2.25,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91,1
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,-2.25,1.92,2.01,1.92,2.00,1.98,2.04,1.91,1.97,2
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,0.00,1.92,2.01,1.94,1.97,1.97,2.06,1.90,1.99,2
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,-2.00,2.07,1.86,2.05,1.86,2.15,1.91,2.03,1.85,2
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,-0.75,1.92,2.01,1.92,2.00,1.95,2.11,1.89,2,0

In [ ]:
matches["HTR_codes"] = matches["HTR"].astype("category").cat.codes

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code,HTR_codes
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,2.03,1.90,1.99,1.93,2.04,1.93,1.98,1.91,1,0
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,1.92,2.01,1.92,2.00,1.98,2.04,1.91,1.97,2,1
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.92,2.01,1.94,1.97,1.97,2.06,1.90,1.99,2,1
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,2.07,1.86,2.05,1.86,2.15,1.91,2.03,1.85,2,1
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,1.92,2.01,1.92,2.00,1.95,2.11,1.89,2,0,0

In [ ]:
matches["opp_codes"] = matches["AwayTeam"].astype("category").cat.codes

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code,HTR_codes,opp_codes
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,1.90,1.99,1.93,2.04,1.93,1.98,1.91,1,0,10
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,2.01,1.92,2.00,1.98,2.04,1.91,1.97,2,1,0
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,2.01,1.94,1.97,1.97,2.06,1.90,1.99,2,1,14
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,1.86,2.05,1.86,2.15,1.91,2.03,1.85,2,1,15
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,2.01,1.92,2.00,1.95,2.11,1.89,2,0,0,7

In [ ]:
matches["team_codes"] = matches["HomeTeam"].astype("category").cat.codes

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code,HTR_codes,opp_codes,team_codes
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,1.99,1.93,2.04,1.93,1.98,1.91,1,0,10,1
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,1.92,2.00,1.98,2.04,1.91,1.97,2,1,0,4
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.94,1.97,1.97,2.06,1.90,1.99,2,1,14,8
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,2.05,1.86,2.15,1.91,2.03,1.85,2,1,15,12
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,1.92,2.00,1.95,2.11,1.89,2,0,0,7,20

In [ ]:
matches["hour"] = matches["Time"].str.replace(":.+", "", regex=True).astype("int")

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code,HTR_codes,opp_codes,team_codes,hour
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,1.93,2.04,1.93,1.98,1.91,1,0,10,1,19
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,2.00,1.98,2.04,1.91,1.97,2,1,0,4,14
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.97,1.97,2.06,1.90,1.99,2,1,14,8,14
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,1.86,2.15,1.91,2.03,1.85,2,1,15,12,14
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,2.00,1.95,2.11,1.89,2,0,0,7,20,14

In [ ]:
matches["day_code"] = matches["Date"].dt.day_of_week

In [ ]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,FTR_code,HTR_codes,opp_codes,team_codes,hour,day_code
0,2019-08-16,19:30,Bayern Munich,Hertha,2,2,D,1,2,A,...,2.04,1.93,1.98,1.91,1,0,10,1,19,4
1,2019-08-17,14:30,Dortmund,Augsburg,5,1,H,1,1,D,...,1.98,2.04,1.91,1.97,2,1,0,4,14,5
2,2019-08-17,14:30,Freiburg,Mainz,3,0,H,0,0,D,...,1.97,2.06,1.90,1.99,2,1,14,8,14,5
3,2019-08-17,14:30,Leverkusen,Paderborn,3,2,H,2,2,D,...,2.15,1.91,2.03,1.85,2,1,15,12,14,5
4,2019-08-17,14:30,Werder Bremen,Fortuna Dusseldorf,1,3,A,0,1,A,...,1.95,2.11,1.89,2,0,0,7,20,14,5

In [ ]:
matches["target"] = (matches["FTR_code"] == 2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf = RandomForestClassifier(n_estimators=100, min_samples_split=10, random_state=0)

In [ ]:
train = matches[matches["Date"] < "27-05-2023"]

In [ ]:
test = current_season